#pragma once

#define VER_PRODUCTBUILD 570
#define VER_PRODUCTVERSION_STR_W L"e2a698d-dev"
#define VER_FILEVERSION_STR_W VER_PRODUCTVERSION_STR_W
#define VER_BRANCHVERSION_STR_W L"DrPerkyLegit/LCEServerTest/main"
#define VER_NETWORK VER_PRODUCTBUILD
